### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by EricHeredia** [zvovov/tvsongs#3]
File "tvsongs", line 171, in main
    _episode_song_count_list[episode_ct] = _episode_json['song_count']
KeyError: 'song_count'

"song_count" needs to be changed to "songs_count"

File "tvsongs", line 172, in main
    _episode_description = _episode_json['episode_description']
KeyError: 'song_count'

"episode_description" needs to be changed to "description"

**Comment by zvovov** [comment]
#4 merged. It fixes this error
